---
- name: Add private ca-cert, if necessary
  copy:
    src: "files/{{ rut_private_cert_file }}"
    dest: "/etc/pki/ca-trust/source/anchors/{{ rut_private_cert_file }}"
  when: rut_private_cert|bool

- name: Check system certificate store hash
  command: sha256sum {{ rut_ca_cert_file }}
  register: rut_ca_hash_before
  when: rut_private_cert|bool
  changed_when: false

- name: Update ca trust with private ca-cert, if necessary
  command: update-ca-trust
  when: rut_private_cert|bool
  changed_when: false

- name: Check system certificate store hash after update ca trust
  command: sha256sum {{ rut_ca_cert_file }}
  register: rut_ca_hash_after
  when: rut_private_cert|bool
  changed_when: false

- name: Check for ca store updates for idempotence
  debug:
    msg: CA store was updated!
  when: (rut_private_cert|bool) and (rut_ca_hash_before.stdout != rut_ca_hash_after.stdout)
  changed_when: true

- name: Update all installed packages
  yum:
    name: '*'
    state: latest

- name: Install package from base repo
  yum:
    name: tree
    state: latest

- name: Install EPEL repo file
  template:
    src: epel_repo.j2
    dest: /etc/yum.repos.d/epel.repo
    owner: root
    group: root
  when: ansible_distribution | lower == 'centos'

- name: Install IUS repo file
  template:
    src: ius_repo.j2
    dest: /etc/yum.repos.d/ius.repo
    owner: root
    group: root
  when: ansible_distribution | lower == 'centos'

- name: Install package from EPEL repo
  yum:
    name: python36
    state: latest
  when: ansible_distribution | lower == 'centos'

- name: Install package from IUS repo
  yum:
    name: git2u
    state: latest
  when: ansible_distribution | lower == 'centos'

- name: Install python virtualenv for pip module use
  yum:
    name: python-virtualenv
    state: latest
  when: ansible_distribution | lower == 'centos'

- name: Install pip3 modules
  pip:
    name: "{{ rut_pip_modules }}"
    virtualenv: /pip_test/venv
    virtualenv_python: python3.6
    extra_args: "-i {{ rut_pypi_index_site }} --trusted-host {{ rut_pypi_trusted_host }}"
    state: latest
  when: ansible_distribution | lower == 'centos'
