---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: instance
    image: ubuntu:14.04
provisioner:
  name: ansible
  lint:
    name: ansible-lint
    options:
      x: ["403"]
verifier:
  name: testinfra
  lint:
    name: flake8
